import type { FC } from 'react';
import type { InputBaseState } from '@porsche-design-system/components/dist/utils';
type InputBaseProps = {
    children?: JSX.Element;
    host: HTMLElement;
    id: string;
    label?: string;
    description?: string;
    loading?: boolean;
    initialLoading?: boolean;
    required?: boolean;
    disabled?: boolean;
    state?: InputBaseState;
    message?: string;
    theme?: any;
    readOnly?: boolean;
    name: string;
    form?: string;
    placeholder?: string;
    maxLength?: number;
    minLength?: number;
    max?: number | string;
    min?: number | string;
    autoComplete?: string;
    pattern?: string;
    multiple?: boolean;
    type: string;
    value?: string;
    step?: number;
    spellCheck?: boolean;
    start?: JSX.Element;
    end?: JSX.Element;
};
export declare const InputBase: FC<InputBaseProps>;
export {};
